/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUserIdRouteImport } from './routes/u.$userId'
import { Route as DmUserIdRouteImport } from './routes/dm.$userId'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as ApiGenerateNameRouteImport } from './routes/api/generate-name'
import { Route as ApiGenerateFirstMessageRouteImport } from './routes/api/generate-first-message'
import { Route as ApiGenerateCharacterImageRouteImport } from './routes/api/generate-character-image'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicHooksSendRemindersRouteImport } from './routes/api/public/hooks/send-reminders'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const DmUserIdRoute = DmUserIdRouteImport.update({
  id: '/dm/$userId',
  path: '/dm/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateNameRoute = ApiGenerateNameRouteImport.update({
  id: '/api/generate-name',
  path: '/api/generate-name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateFirstMessageRoute = ApiGenerateFirstMessageRouteImport.update({
  id: '/api/generate-first-message',
  path: '/api/generate-first-message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateCharacterImageRoute =
  ApiGenerateCharacterImageRouteImport.update({
    id: '/api/generate-character-image',
    path: '/api/generate-character-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSendRemindersRoute =
  ApiPublicHooksSendRemindersRouteImport.update({
    id: '/api/public/hooks/send-reminders',
    path: '/api/public/hooks/send-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/create': typeof CreateRoute
  '/notifications': typeof NotificationsRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-character-image': typeof ApiGenerateCharacterImageRoute
  '/api/generate-first-message': typeof ApiGenerateFirstMessageRoute
  '/api/generate-name': typeof ApiGenerateNameRoute
  '/chat/$id': typeof ChatIdRoute
  '/dm/$userId': typeof DmUserIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/create': typeof CreateRoute
  '/notifications': typeof NotificationsRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-character-image': typeof ApiGenerateCharacterImageRoute
  '/api/generate-first-message': typeof ApiGenerateFirstMessageRoute
  '/api/generate-name': typeof ApiGenerateNameRoute
  '/chat/$id': typeof ChatIdRoute
  '/dm/$userId': typeof DmUserIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/create': typeof CreateRoute
  '/notifications': typeof NotificationsRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-character-image': typeof ApiGenerateCharacterImageRoute
  '/api/generate-first-message': typeof ApiGenerateFirstMessageRoute
  '/api/generate-name': typeof ApiGenerateNameRoute
  '/chat/$id': typeof ChatIdRoute
  '/dm/$userId': typeof DmUserIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chats'
    | '/create'
    | '/notifications'
    | '/premium'
    | '/profile'
    | '/search'
    | '/settings'
    | '/api/chat'
    | '/api/generate-character-image'
    | '/api/generate-first-message'
    | '/api/generate-name'
    | '/chat/$id'
    | '/dm/$userId'
    | '/u/$userId'
    | '/api/public/hooks/send-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chats'
    | '/create'
    | '/notifications'
    | '/premium'
    | '/profile'
    | '/search'
    | '/settings'
    | '/api/chat'
    | '/api/generate-character-image'
    | '/api/generate-first-message'
    | '/api/generate-name'
    | '/chat/$id'
    | '/dm/$userId'
    | '/u/$userId'
    | '/api/public/hooks/send-reminders'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chats'
    | '/create'
    | '/notifications'
    | '/premium'
    | '/profile'
    | '/search'
    | '/settings'
    | '/api/chat'
    | '/api/generate-character-image'
    | '/api/generate-first-message'
    | '/api/generate-name'
    | '/chat/$id'
    | '/dm/$userId'
    | '/u/$userId'
    | '/api/public/hooks/send-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatsRoute: typeof ChatsRoute
  CreateRoute: typeof CreateRoute
  NotificationsRoute: typeof NotificationsRoute
  PremiumRoute: typeof PremiumRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateCharacterImageRoute: typeof ApiGenerateCharacterImageRoute
  ApiGenerateFirstMessageRoute: typeof ApiGenerateFirstMessageRoute
  ApiGenerateNameRoute: typeof ApiGenerateNameRoute
  ChatIdRoute: typeof ChatIdRoute
  DmUserIdRoute: typeof DmUserIdRoute
  UUserIdRoute: typeof UUserIdRoute
  ApiPublicHooksSendRemindersRoute: typeof ApiPublicHooksSendRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dm/$userId': {
      id: '/dm/$userId'
      path: '/dm/$userId'
      fullPath: '/dm/$userId'
      preLoaderRoute: typeof DmUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-name': {
      id: '/api/generate-name'
      path: '/api/generate-name'
      fullPath: '/api/generate-name'
      preLoaderRoute: typeof ApiGenerateNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-first-message': {
      id: '/api/generate-first-message'
      path: '/api/generate-first-message'
      fullPath: '/api/generate-first-message'
      preLoaderRoute: typeof ApiGenerateFirstMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-character-image': {
      id: '/api/generate-character-image'
      path: '/api/generate-character-image'
      fullPath: '/api/generate-character-image'
      preLoaderRoute: typeof ApiGenerateCharacterImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-reminders': {
      id: '/api/public/hooks/send-reminders'
      path: '/api/public/hooks/send-reminders'
      fullPath: '/api/public/hooks/send-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatsRoute: ChatsRoute,
  CreateRoute: CreateRoute,
  NotificationsRoute: NotificationsRoute,
  PremiumRoute: PremiumRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateCharacterImageRoute: ApiGenerateCharacterImageRoute,
  ApiGenerateFirstMessageRoute: ApiGenerateFirstMessageRoute,
  ApiGenerateNameRoute: ApiGenerateNameRoute,
  ChatIdRoute: ChatIdRoute,
  DmUserIdRoute: DmUserIdRoute,
  UUserIdRoute: UUserIdRoute,
  ApiPublicHooksSendRemindersRoute: ApiPublicHooksSendRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
